server:
  port: 8081

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: anagram-angularjs

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true